from src.simulation.persona import LearnerPersona
from src.simulation.scenario import SimulationScenario, SimulationStep


BUILTIN_PERSONAS: dict[str, LearnerPersona] = {
    "grade7_low_vocab": LearnerPersona(
        id="grade7_low_vocab",
        name="Grade 7 low vocabulary learner",
        level="beginner",
        target="grade7_textbook",
        known_words={"hello", "name", "morning"},
        weak_words={"telephone", "number", "friend"},
        weak_patterns={"word_order", "missing_be"},
        motivation=0.7,
        patience=0.6,
        carelessness=0.25,
        hint_acceptance=0.8,
    ),
    "grade7_recognition_only": LearnerPersona(
        id="grade7_recognition_only",
        name="Grade 7 recognition-heavy learner",
        level="beginner",
        target="grade7_textbook",
        known_words={"hello", "morning", "friend"},
        weak_words={"telephone", "number", "spell"},
        weak_patterns={"context_use", "production"},
        motivation=0.75,
        patience=0.7,
    ),
    "cet_transition_weak": LearnerPersona(
        id="cet_transition_weak",
        name="CET writing transition learner",
        level="intermediate",
        target="CET6",
        known_words={"important", "useful", "online"},
        weak_words={"significant", "sustainable", "evidence"},
        weak_patterns={"weak_transition"},
        writing_weaknesses={"overuse_first_second_third"},
        motivation=0.8,
        patience=0.75,
    ),
    "vocabulary_deposit_user": LearnerPersona(
        id="vocabulary_deposit_user",
        name="Vocabulary deposit learner",
        level="intermediate",
        target="CET6",
        known_words={"evidence"},
        weak_words={"significant", "sustainable"},
        weak_patterns=set(),
    ),
    "frustrated_retry_light": LearnerPersona(
        id="frustrated_retry_light",
        name="Easily frustrated learner",
        level="beginner",
        target="grade7_textbook",
        known_words={"hello"},
        weak_words={"telephone", "friend"},
        weak_patterns={"missing_be"},
        motivation=0.45,
        patience=0.35,
        hint_acceptance=0.9,
    ),
}


BUILTIN_SCENARIOS: dict[str, SimulationScenario] = {}


BUILTIN_SCENARIOS.update(
    {
        "daily_lesson_checkpoint_resume_after_restart": SimulationScenario(
            id="daily_lesson_checkpoint_resume_after_restart",
            name="Daily lesson checkpoint resume after restart",
            persona_id="grade7_low_vocab",
            steps=[
                SimulationStep(name="create_learner", action="create_learner"),
                SimulationStep(name="daily_plan", action="daily_plan"),
                SimulationStep(
                    name="start_daily_lesson",
                    action="start_daily_lesson",
                    assertions=[
                        {"type": "equals", "path": "daily_lesson.status", "value": "waiting_user"},
                        {"type": "equals", "path": "daily_lesson.resume_from", "value": "grade_attempt"},
                        {"type": "exists", "path": "daily_lesson.thread_id"},
                        {"type": "exists", "path": "daily_lesson.prompt_payload"},
                    ],
                ),
                SimulationStep(
                    name="submit_daily_lesson_answer",
                    action="submit_daily_lesson_answer",
                    payload={"answer": "Good morning!"},
                    assertions=[
                        {"type": "equals", "path": "answer.status", "value": "completed"},
                        {"type": "equals", "path": "answer.checkpoint_status", "value": "completed"},
                        {"type": "exists", "path": "answer.exercise_attempt_id"},
                        {"type": "exists", "path": "answer.mastery_update"},
                    ],
                ),
                SimulationStep(
                    name="fetch_episode_trace",
                    action="fetch_episode_trace",
                    assertions=[
                        {"type": "equals", "path": "episode_trace.episode.status", "value": "completed"},
                        {"type": "event_exists", "path": "episode_trace.events", "event_type": "graph_interrupted"},
                        {"type": "event_exists", "path": "episode_trace.events", "event_type": "graph_resumed"},
                        {"type": "event_exists", "path": "episode_trace.events", "event_type": "exercise_attempt_created"},
                        {"type": "event_exists", "path": "episode_trace.events", "event_type": "next_action_recommended"},
                    ],
                ),
            ],
            module_tags=["langgraph", "checkpoint", "daily_lesson", "runtime"],
            entrypoints=[
                "/api/learners/{learner_id}/daily-lessons/start",
                "/api/learners/{learner_id}/daily-lessons/{episode_id}/answer",
                "/api/runtime/episodes/{episode_id}",
            ],
            expected_events=[
                "graph_interrupted",
                "graph_resumed",
                "exercise_attempt_created",
                "exercise_graded",
                "mastery_updated",
                "memory_written",
                "review_scheduled",
                "next_action_recommended",
            ],
            expected_tool_calls=["exercise.grade", "mastery.update", "memory.write", "verification.verify_episode"],
            expected_state_changes=["checkpoint_waiting_user", "checkpoint_completed"],
            required_metrics=["api_success_rate", "episode_count", "completed_episode_count"],
            owner_module="daily_lesson",
            change_triggers=[
                "src/graph/**",
                "src/learning/**",
                "src/api/daily_lessons.py",
                "src/runtime/**",
                "src/verification/**",
                "src/simulation/**",
            ],
        ),
        "daily_lesson_missing_answer_must_not_write_memory": SimulationScenario(
            id="daily_lesson_missing_answer_must_not_write_memory",
            name="Daily lesson missing answer must not write memory",
            persona_id="grade7_low_vocab",
            steps=[
                SimulationStep(name="create_learner", action="create_learner"),
                SimulationStep(name="daily_plan", action="daily_plan"),
                SimulationStep(
                    name="start_daily_lesson",
                    action="start_daily_lesson",
                    assertions=[
                        {"type": "equals", "path": "daily_lesson.status", "value": "waiting_user"},
                        {"type": "equals", "path": "daily_lesson.checkpoint_status", "value": "waiting_user"},
                    ],
                ),
                SimulationStep(
                    name="fetch_episode_trace",
                    action="fetch_episode_trace",
                    assertions=[
                        {"type": "equals", "path": "episode_trace.episode.status", "value": "waiting_user"},
                        {"type": "event_exists", "path": "episode_trace.events", "event_type": "graph_interrupted"},
                        {"type": "event_absent", "path": "episode_trace.events", "event_type": "exercise_graded"},
                        {"type": "event_absent", "path": "episode_trace.events", "event_type": "memory_written"},
                    ],
                ),
            ],
            module_tags=["langgraph", "checkpoint", "daily_lesson", "memory"],
            entrypoints=[
                "/api/learners/{learner_id}/daily-lessons/start",
                "/api/runtime/episodes/{episode_id}",
            ],
            expected_events=["graph_interrupted", "task_prepared"],
            expected_tool_calls=[],
            expected_state_changes=["checkpoint_waiting_user"],
            required_metrics=["api_success_rate", "episode_count"],
            owner_module="daily_lesson",
            change_triggers=[
                "src/graph/**",
                "src/learning/**",
                "src/api/daily_lessons.py",
                "src/memory/**",
                "src/simulation/**",
            ],
        ),
        "daily_lesson_verification_failure_blocks_completed_status": SimulationScenario(
            id="daily_lesson_verification_failure_blocks_completed_status",
            name="Daily lesson verification failure blocks completed status",
            persona_id="grade7_low_vocab",
            steps=[
                SimulationStep(name="create_learner", action="create_learner"),
                SimulationStep(name="daily_plan", action="daily_plan"),
                SimulationStep(name="start_daily_lesson", action="start_daily_lesson"),
                SimulationStep(
                    name="submit_daily_lesson_answer",
                    action="submit_daily_lesson_answer",
                    payload={"answer": "Good morning!"},
                    assertions=[
                        {"type": "equals", "path": "answer.verification_status", "value": "failed"},
                        {"type": "not_equals", "path": "answer.status", "value": "completed"},
                    ],
                ),
                SimulationStep(
                    name="fetch_episode_trace",
                    action="fetch_episode_trace",
                    assertions=[
                        {"type": "not_equals", "path": "episode_trace.episode.status", "value": "completed"},
                        {
                            "type": "event_exists",
                            "path": "episode_trace.events",
                            "event_type": "verification_report_generated",
                        },
                        {
                            "type": "verification_check_passed",
                            "path": "episode_trace.verification_report.checks",
                            "check_name": "exercise_graded",
                        },
                    ],
                ),
            ],
            module_tags=["langgraph", "daily_lesson", "verification", "runtime"],
            entrypoints=[
                "/api/learners/{learner_id}/daily-lessons/start",
                "/api/learners/{learner_id}/daily-lessons/{episode_id}/answer",
                "/api/runtime/episodes/{episode_id}",
            ],
            expected_events=["exercise_graded", "verification_report_generated"],
            expected_tool_calls=["exercise.grade", "verification.verify_episode"],
            expected_state_changes=["verification_failed"],
            required_metrics=["api_success_rate", "episode_count", "verification_fail_count"],
            owner_module="verification",
            change_triggers=[
                "src/learning/**",
                "src/runtime/**",
                "src/verification/**",
                "src/simulation/**",
            ],
        ),
        "daily_lesson_wrong_answer_updates_mastery_down": SimulationScenario(
            id="daily_lesson_wrong_answer_updates_mastery_down",
            name="Daily lesson wrong answer updates mastery down",
            persona_id="grade7_low_vocab",
            steps=[
                SimulationStep(name="create_learner", action="create_learner"),
                SimulationStep(name="daily_plan", action="daily_plan"),
                SimulationStep(name="start_daily_lesson", action="start_daily_lesson"),
                SimulationStep(
                    name="submit_wrong_answer",
                    action="submit_daily_lesson_answer",
                    payload={"answer": "I good morning."},
                    assertions=[
                        {"type": "equals", "path": "answer.status", "value": "completed"},
                        {
                            "type": "value_between",
                            "path": "answer.mastery_update.mastery_delta",
                            "min": -1,
                            "max": -0.01,
                        },
                        {"type": "exists", "path": "answer.recommendation_result"},
                    ],
                ),
            ],
            module_tags=["daily_lesson", "mastery", "checkpoint"],
            entrypoints=[
                "/api/learners/{learner_id}/daily-lessons/start",
                "/api/learners/{learner_id}/daily-lessons/{episode_id}/answer",
            ],
            expected_events=["exercise_graded", "mastery_updated", "next_action_recommended"],
            expected_tool_calls=["exercise.grade", "mastery.update"],
            expected_state_changes=["mastery_score_updated"],
            required_metrics=["api_success_rate", "completed_episode_count"],
            owner_module="mastery",
            change_triggers=["src/graph/**", "src/learning/**", "src/mastery/**", "src/simulation/**"],
        ),
        "daily_lesson_correct_answer_updates_mastery_up": SimulationScenario(
            id="daily_lesson_correct_answer_updates_mastery_up",
            name="Daily lesson correct answer updates mastery up",
            persona_id="grade7_low_vocab",
            steps=[
                SimulationStep(name="create_learner", action="create_learner"),
                SimulationStep(name="daily_plan", action="daily_plan"),
                SimulationStep(name="start_daily_lesson", action="start_daily_lesson"),
                SimulationStep(
                    name="submit_correct_answer",
                    action="submit_daily_lesson_answer",
                    payload={"answer": "Good morning!"},
                    assertions=[
                        {"type": "equals", "path": "answer.status", "value": "completed"},
                        {
                            "type": "delta_gte",
                            "path": "answer.mastery_update.mastery_delta",
                            "threshold": 0.01,
                        },
                        {"type": "exists", "path": "answer.review_schedule_result"},
                    ],
                ),
            ],
            module_tags=["daily_lesson", "mastery", "checkpoint"],
            entrypoints=[
                "/api/learners/{learner_id}/daily-lessons/start",
                "/api/learners/{learner_id}/daily-lessons/{episode_id}/answer",
            ],
            expected_events=["exercise_graded", "mastery_updated", "review_scheduled"],
            expected_tool_calls=["exercise.grade", "mastery.update", "review.schedule"],
            expected_state_changes=["mastery_score_updated", "review_schedule_created"],
            required_metrics=["api_success_rate", "completed_episode_count"],
            owner_module="mastery",
            change_triggers=["src/graph/**", "src/learning/**", "src/mastery/**", "src/simulation/**"],
        ),
    }
)


BUILTIN_SCENARIOS.update(
    {
    "smoke_learning_journey": SimulationScenario(
        id="smoke_learning_journey",
        name="Smoke learning journey",
        persona_id="grade7_low_vocab",
        steps=[
            SimulationStep(
                name="create_learner",
                action="create_learner",
                assertions=[{"type": "exists", "path": "json.id"}],
            ),
            SimulationStep(
                name="chat",
                action="chat",
                payload={"message": "I want to practice English vocabulary today."},
                assertions=[
                    {"type": "exists", "path": "json.thread_id"},
                    {"type": "exists", "path": "json.message_id"},
                ],
            ),
            SimulationStep(
                name="memory_summary",
                action="memory_summary",
                assertions=[{"type": "status_code", "path": "status_code", "equals": 200}],
            ),
            SimulationStep(
                name="daily_graph",
                action="daily_graph",
                assertions=[
                    {"type": "not_empty", "path": "graph.input_materials"},
                    {"type": "exists", "path": "graph.agent_feedback"},
                    {"type": "not_empty", "path": "graph.memory_candidates"},
                    {"type": "not_empty", "path": "graph.review_items"},
                ],
            ),
        ],
        module_tags=["chat", "memory", "daily_graph", "runtime"],
        entrypoints=[
            "/api/learners",
            "/api/chat/send",
            "/api/learners/{learner_id}/memory/summary",
            "src.graph.main_graph.daily_lesson_graph",
        ],
        expected_events=[],
        expected_tool_calls=[],
        required_metrics=["api_success_rate", "assertion_pass_rate"],
        owner_module="simulation",
        change_triggers=[
            "src/api/chat.py",
            "src/api/memory.py",
            "src/graph/**",
            "src/memory/**",
            "src/simulation/**",
        ],
    ),
    "vocabulary_agent_deposit": SimulationScenario(
        id="vocabulary_agent_deposit",
        name="Vocabulary agent deposit loop",
        persona_id="vocabulary_deposit_user",
        steps=[
            SimulationStep(name="create_learner", action="create_learner"),
            SimulationStep(
                name="chat_with_vocabulary_skill",
                action="chat",
                payload={
                    "message": "Please explain significant, sustainable, evidence and add them to my vocabulary book.",
                    "skill_id": "vocabulary_deposit",
                },
                assertions=[
                    {"type": "equals", "path": "json.skill_id", "value": "vocabulary_deposit"},
                    {"type": "gte", "path": "vocabulary_agent.saved_count", "value": 1},
                ],
            ),
            SimulationStep(
                name="list_vocabulary",
                action="list_vocabulary",
                assertions=[
                    {"type": "not_empty", "path": "json"},
                    {"type": "gte", "path": "vocabulary.total", "value": 1},
                ],
            ),
        ],
        module_tags=["vocabulary", "memory", "chat"],
        entrypoints=[
            "/api/chat/send",
            "/api/learners/{learner_id}/vocabulary",
        ],
        expected_events=["vocabulary_agent_triggered", "memory_written"],
        expected_tool_calls=[],
        expected_state_changes=["vocabulary_card_saved", "memory_event_written"],
        required_metrics=["api_success_rate", "agent_trigger_count", "memory_write_count"],
        owner_module="vocabulary",
        change_triggers=[
            "src/api/chat.py",
            "src/agents/vocabulary_agent.py",
            "src/memory/**",
            "src/models/vocabulary.py",
            "src/vocabulary/**",
            "src/simulation/**",
        ],
    ),
    "vocabulary_practice_adaptation": SimulationScenario(
        id="vocabulary_practice_adaptation",
        name="Vocabulary practice adaptation",
        persona_id="grade7_low_vocab",
        steps=[
            SimulationStep(name="create_learner", action="create_learner"),
            SimulationStep(
                name="seed_vocabulary",
                action="add_vocabulary",
                payload={"words": ["morning", "telephone", "number", "friend", "significant"]},
                assertions=[{"type": "gte", "path": "vocabulary.total", "value": 5}],
            ),
            SimulationStep(
                name="new_practice_attempt",
                action="vocabulary_practice",
                payload={"mode": "new", "limit": 2},
                assertions=[
                    {"type": "exists", "path": "attempt.attempt_id"},
                    {"type": "exists", "path": "attempt.result"},
                    {"type": "exists", "path": "detail.mastery"},
                    {"type": "exists", "path": "summary.status"},
                ],
            ),
            SimulationStep(
                name="spelling_mistake_attempt",
                action="vocabulary_practice",
                payload={"mode": "spelling", "limit": 1},
                assertions=[
                    {"type": "equals", "path": "attempt.result", "value": "incorrect"},
                    {"type": "exists", "path": "attempt.error_type"},
                    {"type": "not_empty", "path": "detail.mistakes"},
                ],
            ),
        ],
        module_tags=["vocabulary", "mastery", "review", "mistake"],
        entrypoints=[
            "/api/learners/{learner_id}/vocabulary/add",
            "/api/learners/{learner_id}/vocabulary/sessions",
            "/api/learners/{learner_id}/vocabulary/sessions/{session_id}/attempts",
        ],
        expected_events=["vocabulary_attempt_recorded", "mistake_recorded", "review_scheduled"],
        expected_tool_calls=[],
        expected_state_changes=["vocabulary_mastery_updated", "vocabulary_mistake_recorded"],
        required_metrics=["api_success_rate", "memory_write_count", "assertion_pass_rate"],
        owner_module="vocabulary",
        change_triggers=[
            "src/api/vocabulary.py",
            "src/api/vocabulary_learning.py",
            "src/memory/vocabulary_store.py",
            "src/models/vocabulary.py",
            "src/tools/srs.py",
            "src/vocabulary/**",
            "src/simulation/**",
        ],
    ),
    "episode_runtime_knowledge_practice": SimulationScenario(
        id="episode_runtime_knowledge_practice",
        name="Episode runtime knowledge practice",
        persona_id="grade7_low_vocab",
        steps=[
            SimulationStep(
                name="create_learner",
                action="create_learner",
                assertions=[{"type": "exists", "path": "json.id"}],
            ),
            SimulationStep(
                name="daily_plan",
                action="daily_plan",
                assertions=[
                    {"type": "status_code", "path": "status_code", "equals": 200},
                    {"type": "exists", "path": "recommendation_plan.tasks.0.task_spec"},
                ],
            ),
            SimulationStep(
                name="start_daily_lesson",
                action="start_daily_lesson",
                assertions=[
                    {"type": "exists", "path": "daily_lesson.episode_id"},
                    {"type": "exists", "path": "daily_lesson.checkpoint_id"},
                    {"type": "exists", "path": "daily_lesson.task_spec"},
                    {"type": "equals", "path": "daily_lesson.answer_required", "value": True},
                ],
            ),
            SimulationStep(
                name="submit_daily_lesson_answer",
                action="submit_daily_lesson_answer",
                payload={"answer": "Good morning!"},
                assertions=[
                    {"type": "equals", "path": "answer.verification_status", "value": "passed"},
                    {"type": "equals", "path": "answer.checkpoint_status", "value": "completed"},
                    {"type": "exists", "path": "answer.mastery_update"},
                ],
            ),
            SimulationStep(
                name="fetch_episode_trace",
                action="fetch_episode_trace",
                assertions=[
                    {"type": "equals", "path": "episode_trace.episode.status", "value": "completed"},
                    {"type": "equals", "path": "episode_trace.checkpoint.status", "value": "completed"},
                    {"type": "not_empty", "path": "episode_trace.events"},
                    {"type": "not_empty", "path": "episode_trace.tool_calls"},
                    {
                        "type": "event_exists",
                        "path": "episode_trace.events",
                        "event_type": "exercise_graded",
                    },
                    {
                        "type": "event_exists",
                        "path": "episode_trace.events",
                        "event_type": "mastery_updated",
                    },
                    {
                        "type": "event_exists",
                        "path": "episode_trace.events",
                        "event_type": "verification_report_generated",
                    },
                    {"type": "exists", "path": "episode_trace.verification_report"},
                    {
                        "type": "verification_check_passed",
                        "path": "episode_trace.verification_report.checks",
                        "check_name": "exercise_graded",
                    },
                    {
                        "type": "verification_check_passed",
                        "path": "episode_trace.verification_report.checks",
                        "check_name": "mastery_updated",
                    },
                    {
                        "type": "tool_called",
                        "path": "episode_trace.tool_calls",
                        "tool_name": "exercise.grade",
                    },
                    {
                        "type": "tool_called",
                        "path": "episode_trace.tool_calls",
                        "tool_name": "mastery.update",
                    },
                ],
            ),
            SimulationStep(
                name="fetch_verification_report",
                action="fetch_verification_report",
                assertions=[
                    {"type": "equals", "path": "verification_report.status", "value": "passed"},
                    {
                        "type": "verification_check_passed",
                        "path": "verification_report.checks",
                        "check_name": "mastery_updated",
                    },
                    {"type": "no_unexpected_error"},
                ],
            ),
        ],
        module_tags=["runtime", "exercise", "mastery", "memory", "verification"],
        entrypoints=[
            "/api/recommendations/daily-plan",
            "/api/learners/{learner_id}/daily-lessons/start",
            "/api/learners/{learner_id}/daily-lessons/{episode_id}/answer",
            "/api/runtime/episodes/{episode_id}",
            "/api/runtime/episodes/{episode_id}/verification",
        ],
        expected_events=[
            "learner_answer_received",
            "exercise_graded",
            "mastery_updated",
            "memory_written",
            "review_scheduled",
            "episode_completed",
        ],
        expected_tool_calls=[
            "exercise.grade",
            "mastery.update",
            "memory.write",
            "verification.verify_episode",
        ],
        expected_state_changes=["exercise_attempt_saved", "mastery_score_updated", "memory_event_written"],
        required_metrics=[
            "api_success_rate",
            "episode_count",
            "completed_episode_count",
            "verification_pass_count",
            "avg_tool_latency_ms",
        ],
        owner_module="runtime",
        change_triggers=[
            "src/api/daily_lessons.py",
            "src/api/runtime.py",
            "src/learning/**",
            "src/mastery/**",
            "src/memory/**",
            "src/runtime/**",
            "src/verification/**",
            "src/simulation/**",
        ],
    ),
    "daily_lesson_capability_recommendation": SimulationScenario(
        id="daily_lesson_capability_recommendation",
        name="Daily lesson recommends an Explore capability",
        persona_id="grade7_low_vocab",
        steps=[
            SimulationStep(
                name="create_learner",
                action="create_learner",
                assertions=[{"type": "exists", "path": "json.id"}],
            ),
            SimulationStep(
                name="daily_plan",
                action="daily_plan",
                assertions=[
                    {"type": "status_code", "path": "status_code", "equals": 200},
                    {"type": "exists", "path": "recommendation_plan.tasks.0.task_spec"},
                ],
            ),
            SimulationStep(
                name="start_daily_lesson",
                action="start_daily_lesson",
                assertions=[
                    {"type": "exists", "path": "daily_lesson.episode_id"},
                    {"type": "equals", "path": "daily_lesson.answer_required", "value": True},
                ],
            ),
            SimulationStep(
                name="submit_grammar_mistake",
                action="submit_daily_lesson_answer",
                payload={"answer": "I good morning."},
                assertions=[
                    {"type": "equals", "path": "answer.status", "value": "completed"},
                    {"type": "not_empty", "path": "answer.next_capability_recommendations"},
                    {
                        "type": "equals",
                        "path": "answer.next_capability_recommendations.0.capability_id",
                        "value": "grammar-explain",
                    },
                    {
                        "type": "recommendation_contains_capability",
                        "path": "answer.next_capability_recommendations",
                        "capability_id": "grammar-explain",
                    },
                ],
            ),
            SimulationStep(
                name="click_recommendation",
                action="click_capability_recommendation",
                payload={"capability_id": "grammar-explain"},
                assertions=[
                    {"type": "status_code", "path": "status_code", "equals": 200},
                    {
                        "type": "equals",
                        "path": "capability_event.event_type",
                        "value": "explore_capability_clicked",
                    },
                    {
                        "type": "equals",
                        "path": "capability_event.capability_id",
                        "value": "grammar-explain",
                    },
                ],
            ),
            SimulationStep(
                name="fetch_episode_trace",
                action="fetch_episode_trace",
                assertions=[
                    {"type": "equals", "path": "episode_trace.episode.status", "value": "completed"},
                    {
                        "type": "contains",
                        "path": "episode_trace_event_types",
                        "value": "explore_capability_recommended",
                    },
                    {
                        "type": "event_exists",
                        "path": "episode_trace.events",
                        "event_type": "explore_capability_recommended",
                    },
                ],
            ),
        ],
        module_tags=["daily_lesson", "recommendation", "explore", "memory", "verification"],
        entrypoints=[
            "/api/recommendations/daily-plan",
            "/api/learners/{learner_id}/daily-lessons/start",
            "/api/learners/{learner_id}/daily-lessons/{episode_id}/answer",
            "/api/learners/{learner_id}/explore/capabilities/{capability_id}/events",
            "/api/runtime/episodes/{episode_id}",
        ],
        expected_events=[
            "exercise_graded",
            "mastery_updated",
            "explore_capability_recommended",
            "memory_written",
            "episode_completed",
        ],
        expected_tool_calls=[
            "exercise.grade",
            "mastery.update",
            "memory.write",
            "verification.verify_episode",
        ],
        expected_state_changes=["capability_recommendation_created", "capability_event_recorded"],
        required_metrics=[
            "api_success_rate",
            "memory_write_count",
            "episode_count",
            "completed_episode_count",
        ],
        owner_module="explore",
        change_triggers=[
            "src/api/daily_lessons.py",
            "src/api/explore.py",
            "src/explore/**",
            "src/learning/**",
            "src/memory/**",
            "src/recommendation/**",
            "src/verification/**",
            "src/simulation/**",
        ],
    ),
    "daily_lesson_checkpoint_resume": SimulationScenario(
        id="daily_lesson_checkpoint_resume",
        name="Daily lesson checkpoint resume",
        persona_id="grade7_low_vocab",
        steps=[
            SimulationStep(
                name="create_learner",
                action="create_learner",
                assertions=[{"type": "exists", "path": "json.id"}],
            ),
            SimulationStep(
                name="daily_plan",
                action="daily_plan",
                assertions=[
                    {"type": "status_code", "path": "status_code", "equals": 200},
                    {"type": "exists", "path": "recommendation_plan.tasks.0.task_spec"},
                ],
            ),
            SimulationStep(
                name="start_daily_lesson",
                action="start_daily_lesson",
                assertions=[
                    {"type": "equals", "path": "daily_lesson.status", "value": "waiting_user"},
                    {"type": "equals", "path": "daily_lesson.answer_required", "value": True},
                    {"type": "exists", "path": "daily_lesson.checkpoint_id"},
                    {"type": "equals", "path": "daily_lesson.checkpoint_status", "value": "waiting_user"},
                ],
            ),
            SimulationStep(
                name="submit_daily_lesson_answer",
                action="submit_daily_lesson_answer",
                payload={"answer": "Good morning!"},
                assertions=[
                    {"type": "equals", "path": "answer.status", "value": "completed"},
                    {"type": "equals", "path": "answer.checkpoint_status", "value": "completed"},
                    {"type": "exists", "path": "answer.verification_status"},
                ],
            ),
            SimulationStep(
                name="fetch_episode_trace",
                action="fetch_episode_trace",
                assertions=[
                    {"type": "equals", "path": "episode_trace.episode.status", "value": "completed"},
                    {"type": "equals", "path": "episode_trace.checkpoint.status", "value": "completed"},
                    {"type": "not_empty", "path": "episode_trace.events"},
                    {
                        "type": "event_order",
                        "path": "episode_trace.events",
                        "before": "learner_answer_received",
                        "after": "exercise_graded",
                    },
                    {
                        "type": "event_order",
                        "path": "episode_trace.events",
                        "before": "exercise_graded",
                        "after": "mastery_updated",
                    },
                    {
                        "type": "memory_event_type_exists",
                        "path": "episode_trace.events",
                        "event_type": "memory_written",
                    },
                ],
            ),
        ],
        module_tags=[
            "langgraph",
            "checkpoint",
            "daily_lesson",
            "exercise",
            "mastery",
            "memory",
            "verification",
        ],
        entrypoints=[
            "/api/learners/{learner_id}/daily-lessons/start",
            "/api/learners/{learner_id}/daily-lessons/{episode_id}/answer",
            "/api/runtime/episodes/{episode_id}",
        ],
        expected_events=[
            "graph_interrupted",
            "learner_answer_received",
            "exercise_graded",
            "mastery_updated",
            "memory_written",
            "review_scheduled",
            "episode_completed",
        ],
        expected_tool_calls=[
            "exercise.grade",
            "mastery.update",
            "memory.write",
            "verification.verify_episode",
        ],
        expected_state_changes=[
            "checkpoint_waiting_user",
            "checkpoint_completed",
            "mastery_score_updated",
            "memory_event_written",
        ],
        required_metrics=[
            "api_success_rate",
            "episode_count",
            "completed_episode_count",
            "verification_pass_count",
            "avg_tool_latency_ms",
        ],
        owner_module="daily_lesson",
        change_triggers=[
            "src/graph/**",
            "src/learning/**",
            "src/api/daily_lessons.py",
            "src/api/runtime.py",
            "src/mastery/**",
            "src/memory/**",
            "src/runtime/**",
            "src/verification/**",
            "src/simulation/**",
        ],
    ),
    }
)
