from src.explore.schemas import ExploreCapabilitySpec


class ExploreCapabilityRegistry:
    def __init__(self, capabilities: list[ExploreCapabilitySpec]):
        self._capabilities = {item.capability_id: item for item in capabilities}

    def get(self, capability_id: str) -> ExploreCapabilitySpec | None:
        return self._capabilities.get(capability_id.strip())

    def list(
        self,
        *,
        status: str | None = None,
        category: str | None = None,
        ready_only: bool = False,
    ) -> list[ExploreCapabilitySpec]:
        items = list(self._capabilities.values())
        if ready_only:
            items = [item for item in items if item.status == "ready"]
        if status:
            items = [item for item in items if item.status == status]
        if category:
            items = [item for item in items if item.category == category]
        return sorted(items, key=lambda item: (item.category, item.title, item.capability_id))

    def ready(self) -> list[ExploreCapabilitySpec]:
        return self.list(ready_only=True)

    def has_ready(self, capability_id: str) -> bool:
        item = self.get(capability_id)
        return item is not None and item.status == "ready"


def _capability(
    *,
    capability_id: str,
    title: str,
    description: str,
    category: str,
    action: str,
    learning_skill: str,
    supported_target_types: list[str],
    recommended_when: list[str],
    expected_learning_outcome: str,
    status: str = "ready",
    tool_target: str | None = None,
    route_hint: str | None = None,
    supported_error_types: list[str] | None = None,
    not_recommended_when: list[str] | None = None,
    task_type: str | None = None,
    target_type: str | None = None,
    default_difficulty: str | None = None,
    estimated_minutes: int | None = None,
    allowed_tools: list[str] | None = None,
    produces: list[str] | None = None,
    priority_weight: float = 1.0,
    requires_user_input: bool = True,
    metadata: dict | None = None,
) -> ExploreCapabilitySpec:
    return ExploreCapabilitySpec(
        capability_id=capability_id,
        feature_id=capability_id,
        title=title,
        description=description,
        category=category,
        status=status,  # type: ignore[arg-type]
        action=action,  # type: ignore[arg-type]
        tool_target=tool_target,
        route_hint=route_hint,
        learning_skill=learning_skill,
        supported_target_types=supported_target_types,
        supported_error_types=supported_error_types or [],
        recommended_when=recommended_when,
        not_recommended_when=not_recommended_when or [],
        expected_learning_outcome=expected_learning_outcome,
        task_type=task_type,
        target_type=target_type,
        default_difficulty=default_difficulty,
        estimated_minutes=estimated_minutes,
        allowed_tools=allowed_tools or [],
        produces=produces or [],
        priority_weight=priority_weight,
        requires_user_input=requires_user_input,
        metadata=metadata or {},
    )


EXPLORE_CAPABILITIES: dict[str, ExploreCapabilitySpec] = {
    item.capability_id: item
    for item in [
        _capability(
            capability_id="daily-lesson",
            title="开始今日课程",
            description="根据当前目标安排一次综合学习任务。",
            category="exam",
            action="session",
            learning_skill="general",
            supported_target_types=["curriculum_node", "knowledge_point", "general"],
            recommended_when=["learner needs a guided next step", "insufficient context"],
            expected_learning_outcome="完成一次综合练习并沉淀学习记录。",
            task_type="learn_knowledge_point",
            target_type="curriculum_node",
            default_difficulty="adaptive",
            estimated_minutes=15,
            allowed_tools=["rag.retrieve", "exercise.grade", "mastery.update"],
            produces=["attempt", "memory_event", "mastery_update"],
            priority_weight=0.8,
        ),
        _capability(
            capability_id="vocab-review",
            title="复习待掌握词汇",
            description="进入学习中心复习系统安排的词卡。",
            category="vocabulary",
            action="tool",
            tool_target="dashboard",
            learning_skill="vocabulary",
            supported_target_types=["vocabulary", "vocabulary_item", "knowledge_point"],
            supported_error_types=["vocabulary", "word_meaning", "recall", "spelling"],
            recommended_when=["vocabulary recall is weak", "due review exists"],
            expected_learning_outcome="更新词汇熟练度、复习间隔和正确率。",
            task_type="practice_vocabulary",
            target_type="vocabulary",
            default_difficulty="adaptive",
            estimated_minutes=8,
            allowed_tools=["memory.retrieve", "exercise.grade", "mastery.update", "review.schedule"],
            produces=["attempt", "memory_event", "mastery_update", "review_schedule"],
        ),
        _capability(
            capability_id="vocabulary-detail",
            title="词汇详解",
            description="围绕词义、搭配、语境和易错点生成微课。",
            category="vocabulary",
            action="vocabulary-detail",
            learning_skill="vocabulary",
            supported_target_types=["vocabulary", "vocabulary_item", "knowledge_point"],
            supported_error_types=["word_meaning", "collocation", "vocabulary"],
            recommended_when=["word meaning is unclear", "collocation is weak"],
            expected_learning_outcome="理解单词核心义项、搭配、例句和易混点。",
            task_type="practice_vocabulary",
            target_type="vocabulary",
            default_difficulty="adaptive",
            estimated_minutes=8,
            allowed_tools=["memory.retrieve", "exercise.grade"],
            produces=["memory_event"],
            priority_weight=0.95,
        ),
        _capability(
            capability_id="word-roots-affixes",
            title="词根与词缀",
            description="学习常见词根、前缀和后缀，用构词法理解新词。",
            category="vocabulary",
            action="tool",
            tool_target="word-parts",
            learning_skill="vocabulary",
            supported_target_types=["vocabulary", "vocabulary_item", "knowledge_point"],
            supported_error_types=["spelling", "word_form", "word_meaning"],
            recommended_when=["spelling is weak", "word form is confusing"],
            expected_learning_outcome="建立构词法线索，提升猜词和拼写能力。",
            task_type="practice_vocabulary",
            target_type="vocabulary",
            default_difficulty="adaptive",
            estimated_minutes=10,
            allowed_tools=["memory.retrieve", "exercise.grade"],
            produces=["memory_event"],
        ),
        _capability(
            capability_id="add-vocabulary",
            title="AI 词汇讲解沉淀",
            description="从单词、句子或段落中提炼重点词并解释。",
            category="vocabulary",
            action="chat",
            learning_skill="vocabulary",
            supported_target_types=["vocabulary", "text", "knowledge_point"],
            supported_error_types=["vocabulary", "word_meaning"],
            recommended_when=["new vocabulary appears in material"],
            expected_learning_outcome="把高价值词汇讲解沉淀为可复习资产。",
            task_type="practice_vocabulary",
            target_type="vocabulary",
            estimated_minutes=8,
            allowed_tools=["memory.write", "memory.retrieve"],
            produces=["memory_event", "vocabulary_item"],
            metadata={
                "prompt": "请作为 CET 词汇教练，帮我从下面的材料中提炼值得记忆的重点词。",
            },
        ),
        _capability(
            capability_id="vocabulary-manager",
            title="词汇本管理",
            description="手动添加新词、查看待复习词卡。",
            category="vocabulary",
            action="tool",
            tool_target="dashboard",
            learning_skill="vocabulary",
            supported_target_types=["vocabulary", "vocabulary_item"],
            supported_error_types=["vocabulary", "recall", "spelling"],
            recommended_when=["learner wants precise vocabulary control"],
            expected_learning_outcome="创建真实词卡并进入复习计划。",
            task_type="practice_vocabulary",
            target_type="vocabulary",
            estimated_minutes=6,
            allowed_tools=["review.schedule", "memory.write"],
            produces=["vocabulary_item", "review_schedule"],
            priority_weight=0.75,
        ),
        _capability(
            capability_id="cet-reading",
            title="CET 阅读定位训练",
            description="出一题阅读定位题，并逐步讲解解题路径。",
            category="reading",
            action="chat",
            learning_skill="reading",
            supported_target_types=["reading", "knowledge_point", "curriculum_node"],
            supported_error_types=["reading", "定位", "inference", "main_idea", "detail"],
            recommended_when=["reading location or inference errors appear"],
            expected_learning_outcome="训练定位、排除干扰项和错因复盘。",
            task_type="practice_reading",
            target_type="reading",
            estimated_minutes=12,
            allowed_tools=["rag.retrieve", "exercise.grade"],
            produces=["attempt", "feedback"],
            metadata={"prompt": "请作为 CET-6 阅读教练，给我一题转折定位题。"},
        ),
        _capability(
            capability_id="reading-intensive-extensive",
            title="精读与泛读",
            description="同一篇材料，精读看结构，泛读抓主旨。",
            category="reading",
            action="tool",
            tool_target="reading-workshop",
            learning_skill="reading",
            supported_target_types=["reading", "knowledge_point", "curriculum_node"],
            supported_error_types=["reading", "inference", "main_idea", "定位"],
            recommended_when=["learner needs reading structure and gist practice"],
            expected_learning_outcome="获得主旨理解、段落功能和难句拆解训练。",
            task_type="practice_reading",
            target_type="reading",
            estimated_minutes=15,
            allowed_tools=["rag.retrieve", "exercise.grade"],
            produces=["feedback"],
        ),
        _capability(
            capability_id="essay-review",
            title="作文批改",
            description="按四六级写作标准批改结构、语法和用词。",
            category="writing",
            action="chat",
            learning_skill="writing",
            supported_target_types=["writing", "essay", "knowledge_point"],
            supported_error_types=["writing", "grammar", "transition", "cohesion", "low_level_connector"],
            recommended_when=["essay feedback or writing error appears"],
            expected_learning_outcome="得到分项反馈，并沉淀可迁移错因。",
            task_type="practice_writing",
            target_type="writing",
            estimated_minutes=15,
            allowed_tools=["exercise.grade", "memory.write"],
            produces=["feedback", "memory_event"],
            metadata={"prompt": "请作为 CET-4/CET-6 写作老师批改我的作文。"},
        ),
        _capability(
            capability_id="writing-phrasebook",
            title="好句收藏馆",
            description="收藏常用句式、固定搭配和作文高分句，并通过练习掌握。",
            category="writing",
            action="tool",
            tool_target="writing-phrasebook",
            learning_skill="writing",
            supported_target_types=["writing", "writing_phrase", "essay", "knowledge_point"],
            supported_error_types=["writing", "transition", "collocation", "low_level_connector"],
            recommended_when=["writing expression needs reusable phrase assets"],
            expected_learning_outcome="形成个人句式资产库并通过练习检测掌握情况。",
            task_type="practice_writing_phrase",
            target_type="writing_phrase",
            default_difficulty="adaptive",
            estimated_minutes=10,
            allowed_tools=["exercise.grade", "mastery.update", "memory.write"],
            produces=["attempt", "memory_event", "mastery_update"],
            priority_weight=1.05,
        ),
        _capability(
            capability_id="grammar-explain",
            title="语法微知识点",
            description="按分类选择小语法点，生成精讲 HTML。",
            category="grammar",
            action="tool",
            tool_target="grammar",
            learning_skill="grammar",
            supported_target_types=["knowledge_point", "grammar", "curriculum_node"],
            supported_error_types=["grammar", "tense", "clause", "article", "grammar_rule_confusion"],
            recommended_when=["grammar-related mistakes appear", "target is a knowledge point"],
            expected_learning_outcome="集中学透一个小语法规则，并完成配套练习。",
            task_type="learn_knowledge_point",
            target_type="knowledge_point",
            default_difficulty="easy",
            estimated_minutes=6,
            allowed_tools=["rag.retrieve", "exercise.grade", "mastery.update"],
            produces=["attempt", "memory_event", "mastery_update"],
            priority_weight=1.15,
        ),
        _capability(
            capability_id="translation-practice",
            title="翻译练习",
            description="进行中文到英文的四六级翻译训练。",
            category="writing",
            action="chat",
            learning_skill="writing",
            supported_target_types=["writing", "translation", "knowledge_point"],
            supported_error_types=["writing", "translation", "grammar", "collocation"],
            recommended_when=["learner needs sentence restructuring practice"],
            expected_learning_outcome="获得参考译文、表达替换和错误分析。",
            task_type="practice_translation",
            target_type="writing",
            estimated_minutes=12,
            allowed_tools=["exercise.grade", "memory.write"],
            produces=["feedback", "memory_event"],
            metadata={"prompt": "请给我一段 CET-6 风格中文翻译题。"},
        ),
        _capability(
            capability_id="speaking-roleplay",
            title="口语场景模拟",
            description="用文本方式模拟口语对话场景。",
            category="speaking",
            action="chat",
            learning_skill="speaking",
            supported_target_types=["speaking", "pronunciation", "knowledge_point"],
            supported_error_types=["speaking", "fluency", "pronunciation"],
            recommended_when=["speaking confidence or fluency is weak"],
            expected_learning_outcome="获得可跟读表达、追问和口语替换句。",
            task_type="practice_speaking",
            target_type="speaking",
            estimated_minutes=10,
            allowed_tools=["memory.write"],
            produces=["feedback", "memory_event"],
            metadata={"prompt": "请和我进行 CET 口语场景模拟。"},
        ),
        _capability(
            capability_id="phonetic-association",
            title="音标图像联想训练",
            description="用图像联想卡片记住常见音标。",
            category="speaking",
            action="tool",
            tool_target="pronunciation",
            learning_skill="speaking",
            supported_target_types=["pronunciation", "speaking", "vocabulary"],
            supported_error_types=["pronunciation", "phonetic", "spelling"],
            recommended_when=["phonetic awareness or spelling is weak"],
            expected_learning_outcome="补齐音标基础并形成跟读记录。",
            task_type="practice_pronunciation",
            target_type="pronunciation",
            estimated_minutes=10,
            allowed_tools=["memory.write"],
            produces=["memory_event"],
            metadata={"pronunciation_workspace": "phonetic"},
        ),
        _capability(
            capability_id="shadowing",
            title="影子跟读训练",
            description="听一句，跟一句，模仿真实表达的节奏、重音和语调。",
            category="speaking",
            action="tool",
            tool_target="pronunciation",
            learning_skill="speaking",
            supported_target_types=["pronunciation", "speaking", "reading"],
            supported_error_types=["pronunciation", "speaking", "fluency", "rhythm"],
            recommended_when=["speech rhythm or intonation is weak"],
            expected_learning_outcome="获得分块跟读稿、重音提示和口语训练记录。",
            task_type="practice_pronunciation",
            target_type="pronunciation",
            estimated_minutes=10,
            allowed_tools=["memory.write"],
            produces=["memory_event"],
            metadata={"pronunciation_workspace": "shadowing"},
        ),
        _capability(
            capability_id="listening-intensive",
            title="听力音频精听",
            description="上传或选择音频后做逐句精听、听写和跟读。",
            category="listening",
            status="todo",
            action="todo",
            learning_skill="listening",
            supported_target_types=["listening"],
            recommended_when=["listening dictation is needed"],
            expected_learning_outcome="后续支持音频、转写、逐句讲解和复听计划。",
        ),
        _capability(
            capability_id="speaking-record-score",
            title="口语录音评分",
            description="录音后分析发音、流利度和表达自然度。",
            category="speaking",
            status="todo",
            action="todo",
            learning_skill="speaking",
            supported_target_types=["speaking", "pronunciation"],
            recommended_when=["recorded speaking score is needed"],
            expected_learning_outcome="后续接入录音采集和语音评分模型。",
        ),
        _capability(
            capability_id="mock-exam-timer",
            title="真题套卷计时",
            description="按考试时间完成一套题，并输出分项报告。",
            category="exam",
            status="todo",
            action="todo",
            learning_skill="exam",
            supported_target_types=["exam"],
            recommended_when=["mock exam timing is needed"],
            expected_learning_outcome="后续接入真题套卷、计时器和报告生成。",
        ),
        _capability(
            capability_id="error-drill-generator",
            title="错题专项训练",
            description="根据错因自动生成专项训练。",
            category="exam",
            status="todo",
            action="todo",
            learning_skill="general",
            supported_target_types=["error_pattern", "knowledge_point"],
            recommended_when=["top error patterns are available"],
            expected_learning_outcome="后续接入错因到题目生成的完整链路。",
        ),
    ]
}


explore_capability_registry = ExploreCapabilityRegistry(list(EXPLORE_CAPABILITIES.values()))
